# Generated by Django 3.1.4 on 2020-12-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201209_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='main_app.lecture'),
        ),
    ]
