# Generated by Django 3.1.4 on 2020-12-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201210_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_lecture', to='main_app.lecture'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
        ),
    ]
