# Generated by Django 3.1.4 on 2020-12-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201210_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='comment',
        ),
    ]
