# Generated by Django 3.1.4 on 2020-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20201213_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='course_participants', to='main_app.User'),
        ),
    ]
