# Generated by Django 3.1.4 on 2020-12-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20201213_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/lectures/'),
        ),
    ]
